theme: jekyll-theme-tactile
title: BES Playbook
description: The Playbooks will support development and modernization efforts within the BES AFLCMC/HIA Logistic Division as it transforms its methodologies to procure, develop and implement specialized IT products using Agile methodology and best practices as specified via Enterprise Logistics IT. 
